@ECHO OFF
call msg * "YOU HAVE BEEN HACKED!!! WE DETECT THAT YOUR RUNNING ON A RESTRICTED USER MACHINE, HAHAHA! THE ONLY WAY TO STOP THIS IS BY LOGING IN AS A USER WITH ADMIN PRIVLIGES AND REMOVE ME FROM THE REGISTRY..HA GOOD LUCK NEWBBZZZ"
